[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  environment = { ROLLUP_SKIP_NODE_RESOLVE = "true" }

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 