[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  ROLLUP_SKIP_NODE_RESOLVE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 